version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  helloworld:
    lang: go
    handler: ./helloworld
    image: wilsonianb/helloworld:latest
  hellodocker:
    lang: dockerfile
    handler: ./service-deployment
    image: service-deployment:latest
    environment:
      write_debug: true
  goto:
    lang: node10-express
    handler: ./goto
    image: goto:latest
    environment:
      write_debug: true
  network-policy-test:
    lang: dockerfile
    handler: ./network-policy-test
    image: network-policy-test:latest
    environment:
      write_debug: true
